using System;
using System.IO;
using System.Reflection;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;
using PlayerPrefs = MythwakePreferences;
using RawPlayerPrefs = UnityEngine.PlayerPrefs;

/// <summary>Uses only generated test-owned sentinel keys, never existing player values.</summary>
public static class MythwakePreferencesValidation
{
    [MenuItem("Mythwake/Tests/Validate Isolated Preferences")]
    public static void Run()
    {
        RequireTestProfile();
        ValidateArgumentParser();
        ValidateProjectRouting();
        ValidateSentinelIsolation();
        Debug.Log("Mythwake preferences isolation passed for profile " + MythwakePreferences.TestProfileId +
            ": argument validation, all project callers, typed values, defaults, delete and namespace independence. Existing player values were not read.");
    }

    public static void RequireTestProfile()
    {
        if (!MythwakePreferences.IsTestProfileActive)
            throw new InvalidOperationException("This QA entry point requires an Editor launch with -mythwakeTestProfile followed by a unique profile ID.");
    }

    private static void ValidateArgumentParser()
    {
        var parse = typeof(MythwakePreferences).GetMethod("ParseEditorTestProfile", BindingFlags.Static | BindingFlags.NonPublic);
        Require(parse != null, "Editor test profile parser is missing.");
        Require((string)parse.Invoke(null, new object[] { new[] { "Unity.exe", "-batchmode" } }) == string.Empty,
            "Normal Editor launches must preserve existing keys.");
        Require((string)parse.Invoke(null, new object[] { new[] { "Unity.exe", "-mythwakeTestProfile", "qa_42-A", "-batchmode" } }) == "qa_42-A",
            "Explicit profile ID was not preserved.");
        foreach (var arguments in new[]
        {
            new[] { "-mythwakeTestProfile" },
            new[] { "-mythwakeTestProfile", "" },
            new[] { "-mythwakeTestProfile", "../player" },
            new[] { "-mythwakeTestProfile", "contains.dot" },
            new[] { "-mythwakeTestProfile", "contains space" },
            new[] { "-mythwakeTestProfile", new string('a', 65) },
            new[] { "-mythwakeTestProfile", "one", "-mythwakeTestProfile", "two" }
        })
        {
            var rejected = false;
            try { parse.Invoke(null, new object[] { arguments }); }
            catch (TargetInvocationException exception) when (exception.InnerException is ArgumentException) { rejected = true; }
            Require(rejected, "Invalid or ambiguous profile arguments were accepted.");
        }
    }

    private static void ValidateProjectRouting()
    {
        // Inspect common preference callers only; do not load character art or controller sources.
        var directory = Path.Combine(Application.dataPath, "_Mythwake/Scripts");
        foreach (var fileName in new[] { "IdlePrototypeController.cs", "MythwakeBackendClient.cs" })
        {
            var source = File.ReadAllText(Path.Combine(directory, fileName));
            Require(source.Contains("using PlayerPrefs = MythwakePreferences;"), "Preference isolation alias missing: " + fileName);
            Require(!Regex.IsMatch(source, @"\bUnityEngine\s*\.\s*PlayerPrefs\s*\."), "Direct preferences access bypasses test profile: " + fileName);
        }
    }

    private static void ValidateSentinelIsolation()
    {
        var key = "Mythwake.PreferenceIsolationSentinel." + Guid.NewGuid().ToString("N");
        var keys = new[] { key + ".int", key + ".float", key + ".string", key + ".missing" };
        var prefix = "Mythwake.TestProfiles." + MythwakePreferences.TestProfileId + ".";
        var otherPrefix = "Mythwake.TestProfiles.other-" + Guid.NewGuid().ToString("N") + ".";
        try
        {
            // These unprefixed sentinels are generated by this test, not real save/session keys.
            RawPlayerPrefs.SetInt(keys[0], 117);
            RawPlayerPrefs.SetFloat(keys[1], 2.25f);
            RawPlayerPrefs.SetString(keys[2], "test-owned original namespace");
            RawPlayerPrefs.SetString(otherPrefix + keys[2], "test-owned other profile");

            Require(!PlayerPrefs.HasKey(keys[0]), "Test profile can see an unprefixed key.");
            Require(PlayerPrefs.GetInt(keys[0], 61) == 61, "Int lookup leaked from ordinary namespace.");
            Require(PlayerPrefs.GetFloat(keys[1], 6.5f) == 6.5f, "Float lookup leaked from ordinary namespace.");
            Require(PlayerPrefs.GetString(keys[2], "absent") == "absent", "String lookup leaked from ordinary namespace.");
            Require(PlayerPrefs.GetInt(keys[3]) == 0 && PlayerPrefs.GetFloat(keys[3]) == 0f && PlayerPrefs.GetString(keys[3]) == string.Empty,
                "Default overload behavior changed.");

            PlayerPrefs.SetInt(keys[0], 231);
            PlayerPrefs.SetFloat(keys[1], 3.75f);
            PlayerPrefs.SetString(keys[2], "isolated test value");
            PlayerPrefs.Save();
            Require(PlayerPrefs.HasKey(keys[0]) && PlayerPrefs.GetInt(keys[0]) == 231, "Int round trip failed.");
            Require(PlayerPrefs.GetFloat(keys[1]) == 3.75f && PlayerPrefs.GetString(keys[2]) == "isolated test value", "Typed round trip failed.");
            Require(RawPlayerPrefs.GetInt(prefix + keys[0]) == 231, "Value was not written under the explicit profile prefix.");

            foreach (var item in keys) PlayerPrefs.DeleteKey(item);
            PlayerPrefs.Save();
            Require(!PlayerPrefs.HasKey(keys[0]) && !RawPlayerPrefs.HasKey(prefix + keys[0]), "Delete did not remove the isolated value.");
            Require(RawPlayerPrefs.GetInt(keys[0]) == 117 && RawPlayerPrefs.GetFloat(keys[1]) == 2.25f &&
                RawPlayerPrefs.GetString(keys[2]) == "test-owned original namespace", "Profile writes/deletes affected ordinary namespace sentinels.");
            Require(RawPlayerPrefs.GetString(otherPrefix + keys[2]) == "test-owned other profile", "A different profile was affected.");
        }
        finally
        {
            foreach (var item in keys)
            {
                RawPlayerPrefs.DeleteKey(item);
                RawPlayerPrefs.DeleteKey(prefix + item);
                RawPlayerPrefs.DeleteKey(otherPrefix + item);
            }
            RawPlayerPrefs.Save();
        }
    }

    private static void Require(bool condition, string message)
    {
        if (!condition) throw new InvalidOperationException(message);
    }
}

public static class KaelValidationSuite
{
    // CurrentSliceValidation includes destructive progression fixtures. The required process
    // namespace isolates those fixtures and session caches before any controller is created.
    public static void RunAll()
    {
        MythwakePreferencesValidation.Run();
        KaelRosterValidation.Run();
        KaelAnimationValidation.Run();
        KaelCombatSessionValidation.Run();
        KaelFocusClockValidation.Run();
        KaelBackendRetryValidation.Run();
        CurrentSliceValidation.RunCurrentSliceValidation();
    }
}
