using System.Collections.Generic;

public static partial class MythwakeLocalization
{
    private static readonly Dictionary<string, string> English = new Dictionary<string, string>
    {
        { "language.english", "English" },
        { "language.german", "German" },
        { "language.button", "Lang: EN" },
        { "language.changed", "Language set to English." },

        { "ui.menu.header", "Quests & Systems" },
        { "ui.menu.language_title", "Language" },
        { "ui.inventory.title", "Bag" },
        { "ui.inventory.tab.misc", "Misc" },
        { "ui.inventory.tab.gear", "Gear" },
        { "ui.inventory.tab.all", "All" },
        { "ui.inventory.empty.misc", "No misc items yet. Currencies and heroes stay in their own screens." },
        { "ui.inventory.empty.gear", "No gear items in the bag yet. Gear Dungeon drops will appear here." },
        { "ui.inventory.showing", "{0} | Showing {1}/{2} items" },
        { "ui.inventory.count.one", "{0} | {1} item" },
        { "ui.inventory.count.many", "{0} | {1} items" },
        { "ui.inventory.detail.close", "X" },

        { "ui.common.level_short", "Lv" },
        { "ui.common.level", "Level" },
        { "ui.common.max_level", "Max Level" },
        { "ui.common.power", "Power" },
        { "ui.common.team_power", "Team Power" },
        { "ui.common.stage", "Stage" },
        { "ui.common.campaign", "Campaign" },
        { "ui.common.recommended_power", "Recommended Power" },
        { "ui.common.enemy_hp", "Enemy HP" },
        { "ui.common.enemy_damage", "Enemy Damage" },
        { "ui.common.reward", "Reward" },
        { "ui.common.boss_hp", "Boss HP" },
        { "ui.common.formation", "Formation" },
        { "ui.common.cost", "Cost" },
        { "ui.common.sources", "Sources" },
        { "ui.common.visible_in", "Visible in" },
        { "ui.common.next_upgrade", "Next upgrade" },
        { "ui.common.owned", "Owned" },
        { "ui.common.bag", "Bag" },
        { "ui.common.equipped", "Equipped" },
        { "ui.common.copies", "Copies" },
        { "ui.common.empty", "Empty" },
        { "ui.common.locked", "Locked" },
        { "ui.common.tap_to_equip", "Tap to equip" },
        { "ui.common.no_copy", "No copy" },
        { "ui.common.open_gear", "Open Gear screen for {0}" },

        { "currency.gold.name", "Gold" },
        { "currency.gems.name", "Gems" },
        { "currency.myth_essence.name", "Myth Essence" },
        { "currency.pass_xp.name", "Pass XP" },

        { "role.warrior.name", "Warrior" },
        { "role.tank.name", "Tank" },
        { "role.mage.name", "Mage" },
        { "role.ranger.name", "Ranger" },
        { "role.support.name", "Support" },

        { "rarity.rare.name", "Rare" },
        { "rarity.epic.name", "Epic" },
        { "rarity.legendary.name", "Legendary" },

        { "hero.hero_astra.name", "Astra" },
        { "hero.hero_astra.title", "The Frost Vanguard" },
        { "hero.hero_astra.description", "A front-line duelist who turns pressure into steady damage." },
        { "hero.hero_astra.ability.name", "Glacial Charge" },
        { "hero.hero_astra.ability.description", "Astra surges into the enemy line and deals heavy physical damage." },
        { "hero.hero_borin.name", "Borin" },
        { "hero.hero_borin.title", "The Iron Sentinel" },
        { "hero.hero_borin.description", "A durable tank who keeps the team standing through long fights." },
        { "hero.hero_borin.ability.name", "Anvil Guard" },
        { "hero.hero_borin.ability.description", "Borin braces behind his shield and reduces incoming damage." },
        { "hero.hero_cyra.name", "Cyra" },
        { "hero.hero_cyra.title", "The Burning Light" },
        { "hero.hero_cyra.description", "A ranged mage who burns through clustered enemies." },
        { "hero.hero_cyra.ability.name", "Solar Flare" },
        { "hero.hero_cyra.ability.description", "Cyra releases a burst of fire that strikes the target area." },
        { "hero.hero_dante.name", "Dante" },
        { "hero.hero_dante.title", "The Rift Marksman" },
        { "hero.hero_dante.description", "A precise ranger who finishes weakened enemies." },
        { "hero.hero_dante.ability.name", "Rift Shot" },
        { "hero.hero_dante.ability.description", "Dante marks a weak point and fires a high-crit projectile." },
        { "hero.hero_elowen.name", "Elowen" },
        { "hero.hero_elowen.title", "The Grove Oracle" },
        { "hero.hero_elowen.description", "A legendary support who heals allies while boosting tempo." },
        { "hero.hero_elowen.ability.name", "Verdant Prayer" },
        { "hero.hero_elowen.ability.description", "Elowen restores ally health and strengthens the formation." },
        { "hero.hero_ravik.name", "Ravik" },
        { "hero.hero_ravik.title", "The Cinder Prodigy" },
        { "hero.hero_ravik.description", "A volatile mage who spikes damage during ultimate windows." },
        { "hero.hero_ravik.ability.name", "Cinder Nova" },
        { "hero.hero_ravik.ability.description", "Ravik detonates stored flame into a wide magical blast." },

        { "equipment.equipment_weapon.name", "Weapon" },
        { "equipment.equipment_weapon.description", "The active weapon track for {0}. Upgrade it from the Gear screen to raise this hero's attack." },
        { "equipment.equipment_armor.name", "Armor" },
        { "equipment.equipment_armor.description", "The active armor track for {0}. Upgrade it from the Gear screen to improve survivability." },

        { "accessory.item_slot_earrings.name", "Earrings" },
        { "accessory.item_slot_necklace.name", "Necklace" },
        { "accessory.item_slot_bracelet.name", "Bracelet" },
        { "accessory.item_slot_gloves.name", "Gloves" },
        { "accessory.item_slot_shoes.name", "Shoes" },
        { "accessory.description", "Accessory loot from Gear Dungeon. Copies can be equipped on heroes or fused upward from the Hero gear panel." },
        { "accessory.fuse.max", "Fuse: max rarity" },
        { "accessory.fuse.next", "Fuse: {0} copies -> {1}" },
        { "accessory.stats", "Owned {0} | Bag {1} | Equipped {2}\nLv 1: +{3} ATK, +{4} HP\nMax Lv {5}: +{6} ATK, +{7} HP\n{8}" },

        { "dungeon.gold_dungeon.name", "Gold Dungeon" },
        { "dungeon.gold_dungeon.set", "Gold Treasury Set" },
        { "dungeon.gold_dungeon.boss", "Treasure Golem" },
        { "dungeon.essence_dungeon.name", "Essence Dungeon" },
        { "dungeon.essence_dungeon.set", "Rift Essence Set" },
        { "dungeon.essence_dungeon.boss", "Rift Dragon" },
        { "dungeon.gear_dungeon.name", "Gear Dungeon" },
        { "dungeon.gear_dungeon.set", "Iron Armory Set" },
        { "dungeon.gear_dungeon.boss", "Iron Hound" },
        { "dungeon.default_result", "Dungeons are the active resource source." },
        { "dungeon.progress_line", "Progress: <color=#F8E85A>{0}/{1}</color>   Floor {2}" },
        { "dungeon.meta.reward", "{0} | Rec {1} | +{2} {3}" },
        { "dungeon.meta.drop", "{0} | Rec {1} | Accessory drop" },
        { "dungeon.preview.reward", "{0} F{1}  Rec {2}\nBoss HP {3}  +{4} {5}" },
        { "dungeon.preview.drop", "{0} F{1}  Rec {2}\nBoss HP {3}  Accessory drop" },
        { "dungeon.reward.drop", "Reward: random accessory drop" },
        { "dungeon.reward.currency", "Reward: +{0} {1}" },

        { "item.mission_xp.name", "Mission XP" },
        { "item.mission_xp.detail", "Mission Track" },
        { "item.mission_xp.description", "Progress earned from daily missions. It advances the Mission Track and unlocks claimable reward steps." },
        { "item.mission_xp.stats", "Stored XP: {0}\nVisible in: {1}\nSources: daily mission claims" },

        { "summon.banner.hero_shard_standard.name", "Awaken Heroes" },
        { "summon.banner.hero_shard_standard.promo", "First x10 pack has a 10% discount" },
        { "summon.banner.hero_shard_vanguard.name", "Vanguard Oath" },
        { "summon.banner.hero_shard_vanguard.promo", "Higher Epic chance for frontline teams" },
        { "summon.banner.hero_shard_mystic.name", "Mystic Bloom" },
        { "summon.banner.hero_shard_mystic.promo", "Better Legendary odds for support and mages" },
        { "summon.result.title", "Summon Results" }
    };
}
