using System.Collections.Generic;

public static partial class MythwakeLocalization
{
    private static readonly Dictionary<string, string> German = new Dictionary<string, string>
    {
        { "language.english", "Englisch" },
        { "language.german", "Deutsch" },
        { "language.button", "Sprache: DE" },
        { "language.changed", "Sprache auf Deutsch gesetzt." },

        { "ui.menu.header", "Aufgaben & Systeme" },
        { "ui.menu.language_title", "Sprache" },
        { "ui.inventory.title", "Inventar" },
        { "ui.inventory.tab.misc", "Sonstiges" },
        { "ui.inventory.tab.gear", "Ausrüstung" },
        { "ui.inventory.tab.all", "Alles" },
        { "ui.inventory.empty.misc", "Noch keine sonstigen Gegenstände. Währungen und Helden bleiben in ihren eigenen Ansichten." },
        { "ui.inventory.empty.gear", "Noch keine Ausrüstung im Inventar. Beute aus dem Ausrüstungs-Dungeon erscheint hier." },
        { "ui.inventory.showing", "{0} | Zeige {1}/{2} Gegenstände" },
        { "ui.inventory.count.one", "{0} | {1} Gegenstand" },
        { "ui.inventory.count.many", "{0} | {1} Gegenstände" },
        { "ui.inventory.detail.close", "X" },

        { "ui.common.level_short", "Lv" },
        { "ui.common.level", "Level" },
        { "ui.common.max_level", "Max. Level" },
        { "ui.common.power", "Macht" },
        { "ui.common.team_power", "Team-Macht" },
        { "ui.common.stage", "Stufe" },
        { "ui.common.campaign", "Kampagne" },
        { "ui.common.recommended_power", "Empfohlene Macht" },
        { "ui.common.enemy_hp", "Gegner-HP" },
        { "ui.common.enemy_damage", "Gegnerschaden" },
        { "ui.common.reward", "Belohnung" },
        { "ui.common.boss_hp", "Boss-HP" },
        { "ui.common.formation", "Formation" },
        { "ui.common.cost", "Kosten" },
        { "ui.common.sources", "Quellen" },
        { "ui.common.visible_in", "Sichtbar in" },
        { "ui.common.next_upgrade", "Nächstes Upgrade" },
        { "ui.common.owned", "Besitz" },
        { "ui.common.bag", "Inventar" },
        { "ui.common.equipped", "Ausgerüstet" },
        { "ui.common.copies", "Kopien" },
        { "ui.common.empty", "Leer" },
        { "ui.common.locked", "Gesperrt" },
        { "ui.common.tap_to_equip", "Tippen zum Ausrüsten" },
        { "ui.common.no_copy", "Keine Kopie" },
        { "ui.common.open_gear", "Ausrüstung für {0} öffnen" },

        { "currency.gold.name", "Gold" },
        { "currency.gems.name", "Edelsteine" },
        { "currency.myth_essence.name", "Mythos-Essenz" },
        { "currency.pass_xp.name", "Pass-EP" },

        { "role.warrior.name", "Krieger" },
        { "role.tank.name", "Tank" },
        { "role.mage.name", "Magier" },
        { "role.ranger.name", "Schütze" },
        { "role.support.name", "Unterstützung" },

        { "rarity.rare.name", "Selten" },
        { "rarity.epic.name", "Episch" },
        { "rarity.legendary.name", "Legendär" },

        { "hero.hero_astra.name", "Astra" },
        { "hero.hero_astra.title", "Die Frost-Vorhut" },
        { "hero.hero_astra.description", "Eine Frontkämpferin, die Druck in stetigen Schaden verwandelt." },
        { "hero.hero_astra.ability.name", "Gletscheransturm" },
        { "hero.hero_astra.ability.description", "Astra stürmt in die gegnerische Linie und verursacht hohen physischen Schaden." },
        { "hero.hero_borin.name", "Borin" },
        { "hero.hero_borin.title", "Der eiserne Wächter" },
        { "hero.hero_borin.description", "Ein widerstandsfähiger Tank, der das Team in langen Kämpfen am Leben hält." },
        { "hero.hero_borin.ability.name", "Ambosswacht" },
        { "hero.hero_borin.ability.description", "Borin stemmt sich hinter sein Schild und verringert eingehenden Schaden." },
        { "hero.hero_cyra.name", "Cyra" },
        { "hero.hero_cyra.title", "Das brennende Licht" },
        { "hero.hero_cyra.description", "Eine Fernkampfmagierin, die gruppierte Gegner verbrennt." },
        { "hero.hero_cyra.ability.name", "Sonnenflackern" },
        { "hero.hero_cyra.ability.description", "Cyra entfesselt eine Feuerexplosion, die den Zielbereich trifft." },
        { "hero.hero_dante.name", "Dante" },
        { "hero.hero_dante.title", "Der Riss-Schütze" },
        { "hero.hero_dante.description", "Ein präziser Schütze, der geschwächte Gegner erledigt." },
        { "hero.hero_dante.ability.name", "Rissschuss" },
        { "hero.hero_dante.ability.description", "Dante markiert eine Schwachstelle und feuert ein kritisches Projektil ab." },
        { "hero.hero_elowen.name", "Elowen" },
        { "hero.hero_elowen.title", "Das Hain-Orakel" },
        { "hero.hero_elowen.description", "Eine legendäre Unterstützung, die Verbündete heilt und das Tempo erhöht." },
        { "hero.hero_elowen.ability.name", "Grünes Gebet" },
        { "hero.hero_elowen.ability.description", "Elowen stellt Gesundheit wieder her und stärkt die Formation." },
        { "hero.hero_ravik.name", "Ravik" },
        { "hero.hero_ravik.title", "Das Asche-Wunderkind" },
        { "hero.hero_ravik.description", "Ein unberechenbarer Magier, der in Ultimative-Fenstern hohen Schaden verursacht." },
        { "hero.hero_ravik.ability.name", "Asche-Nova" },
        { "hero.hero_ravik.ability.description", "Ravik entzündet gespeicherte Flammen zu einer breiten magischen Explosion." },

        { "equipment.equipment_weapon.name", "Waffe" },
        { "equipment.equipment_weapon.description", "Die aktive Waffenleiste für {0}. Verbessere sie im Ausrüstungsbildschirm, um den Angriff dieses Helden zu erhöhen." },
        { "equipment.equipment_armor.name", "Rüstung" },
        { "equipment.equipment_armor.description", "Die aktive Rüstungsleiste für {0}. Verbessere sie im Ausrüstungsbildschirm, um die Überlebensfähigkeit zu erhöhen." },

        { "accessory.item_slot_earrings.name", "Ohrringe" },
        { "accessory.item_slot_necklace.name", "Kette" },
        { "accessory.item_slot_bracelet.name", "Armband" },
        { "accessory.item_slot_gloves.name", "Handschuhe" },
        { "accessory.item_slot_shoes.name", "Schuhe" },
        { "accessory.description", "Beute aus dem Ausrüstungs-Dungeon. Kopien können Helden ausgerüstet oder im Helden-Ausrüstungsfenster fusioniert werden." },
        { "accessory.fuse.max", "Fusion: höchste Seltenheit" },
        { "accessory.fuse.next", "Fusion: {0} Kopien -> {1}" },
        { "accessory.stats", "Besitz {0} | Inventar {1} | Ausgerüstet {2}\nLv 1: +{3} ATK, +{4} HP\nMax Lv {5}: +{6} ATK, +{7} HP\n{8}" },

        { "dungeon.gold_dungeon.name", "Gold-Dungeon" },
        { "dungeon.gold_dungeon.set", "Goldschatz-Set" },
        { "dungeon.gold_dungeon.boss", "Schatzgolem" },
        { "dungeon.essence_dungeon.name", "Essenz-Dungeon" },
        { "dungeon.essence_dungeon.set", "Riss-Essenz-Set" },
        { "dungeon.essence_dungeon.boss", "Rissdrache" },
        { "dungeon.gear_dungeon.name", "Ausrüstungs-Dungeon" },
        { "dungeon.gear_dungeon.set", "Eiserne Waffenkammer" },
        { "dungeon.gear_dungeon.boss", "Eisenhund" },
        { "dungeon.default_result", "Dungeons sind die aktive Quelle für Ressourcen." },
        { "dungeon.progress_line", "Fortschritt: <color=#F8E85A>{0}/{1}</color>   Etage {2}" },
        { "dungeon.meta.reward", "{0} | Empf. {1} | +{2} {3}" },
        { "dungeon.meta.drop", "{0} | Empf. {1} | Ausrüstungsbeute" },
        { "dungeon.preview.reward", "{0} F{1}  Empf. {2}\nBoss-HP {3}  +{4} {5}" },
        { "dungeon.preview.drop", "{0} F{1}  Empf. {2}\nBoss-HP {3}  Ausrüstungsbeute" },
        { "dungeon.reward.drop", "Belohnung: zufällige Ausrüstungsbeute" },
        { "dungeon.reward.currency", "Belohnung: +{0} {1}" },

        { "item.mission_xp.name", "Missions-EP" },
        { "item.mission_xp.detail", "Missionspfad" },
        { "item.mission_xp.description", "Fortschritt aus täglichen Missionen. Er füllt den Missionspfad und schaltet Belohnungsstufen frei." },
        { "item.mission_xp.stats", "Gespeicherte EP: {0}\nSichtbar in: {1}\nQuellen: tägliche Missionsbelohnungen" },

        { "summon.banner.hero_shard_standard.name", "Helden erwecken" },
        { "summon.banner.hero_shard_standard.promo", "Das erste x10-Paket hat 10% Rabatt" },
        { "summon.banner.hero_shard_vanguard.name", "Schwur der Vorhut" },
        { "summon.banner.hero_shard_vanguard.promo", "Höhere epische Chance für Frontteams" },
        { "summon.banner.hero_shard_mystic.name", "Mystische Blüte" },
        { "summon.banner.hero_shard_mystic.promo", "Bessere legendäre Chancen für Unterstützung und Magier" },
        { "summon.result.title", "Beschwörungsergebnisse" }
    };
}
