using System.Collections.Generic;

public static partial class MythwakeLocalization
{
    private static readonly Dictionary<string, string> German = new Dictionary<string, string>
    {
        { "language.english", "Englisch" },
        { "language.german", "Deutsch" },
        { "language.button", "Sprache: DE" },
        { "language.changed", "Sprache auf Deutsch gesetzt." },

        { "ui.menu.header", "Aufgaben & Systeme" },
        { "ui.menu.language_title", "Sprache" },
        { "ui.inventory.title", "Inventar" },
        { "ui.inventory.tab.misc", "Sonstiges" },
        { "ui.inventory.tab.gear", "Ausrüstung" },
        { "ui.inventory.tab.all", "Alles" },
        { "ui.inventory.empty.misc", "Noch keine sonstigen Gegenstände. Währungen und Helden bleiben in ihren eigenen Ansichten." },
        { "ui.inventory.empty.gear", "Noch keine Ausrüstung im Inventar. Beute aus dem Ausrüstungs-Dungeon erscheint hier." },
        { "ui.inventory.showing", "{0} | Zeige {1}/{2} Gegenstände" },
        { "ui.inventory.count.one", "{0} | {1} Gegenstand" },
        { "ui.inventory.count.many", "{0} | {1} Gegenstände" },
        { "ui.inventory.detail.close", "X" },

        { "ui.common.level_short", "Lv" },
        { "ui.common.level", "Level" },
        { "ui.common.level_up", "Verbessern" },
        { "ui.common.max_level", "Max. Level" },
        { "ui.common.power", "Macht" },
        { "ui.common.team_power", "Team-Macht" },
        { "ui.common.stage", "Stufe" },
        { "ui.common.campaign", "Kampagne" },
        { "ui.common.recommended_power", "Empfohlene Macht" },
        { "ui.common.enemy_hp", "Gegner-HP" },
        { "ui.common.enemy_damage", "Gegnerschaden" },
        { "ui.common.reward", "Belohnung" },
        { "ui.common.boss_hp", "Boss-HP" },
        { "ui.common.formation", "Formation" },
        { "ui.common.cost", "Kosten" },
        { "ui.common.sources", "Quellen" },
        { "ui.common.visible_in", "Sichtbar in" },
        { "ui.common.next_upgrade", "Nächstes Upgrade" },
        { "ui.common.owned", "Besitz" },
        { "ui.common.bag", "Inventar" },
        { "ui.common.equipped", "Ausgerüstet" },
        { "ui.common.training", "Training" },
        { "ui.common.copies", "Kopien" },
        { "ui.common.empty", "Leer" },
        { "ui.common.locked", "Gesperrt" },
        { "ui.common.floor", "Etage" },
        { "ui.common.max", "Max" },
        { "ui.common.tap_to_equip", "Tippen zum Ausrüsten" },
        { "ui.common.no_copy", "Keine Kopie" },
        { "ui.common.equip_gear", "Anlegen" },
        { "ui.common.open_gear_short", "Oeffnen" },
        { "ui.common.remove_gear", "Ablegen" },
        { "ui.common.open_gear", "Ausrüstung für {0} öffnen" },
        { "gear.selected_rarity", "Auswahl-Rang: {0}" },
        { "gear.training_title", "Waffen-/Ruestungs-Training" },
        { "gear.accessory_title", "Accessoire-Feinschliff" },
        { "gear.slot_nav", "Slot: {0}" },
        { "gear.rarity_nav", "Rang: {0}" },
        { "gear.equip_rarity", "{0} anlegen" },
        { "gear.level_equipped", "Angelegtes leveln" },
        { "gear.no_item", "Kein Item" },
        { "gear.fuse_rarity", "{0}x {1} fusionieren" },
        { "gear.fuse_into", "Zu {0}" },
        { "gear.fuse_need_copies", "Brauche {0} Kopien" },
        { "gear.tap_for_details", "Details antippen" },
        { "gear.equip_confirm", "Ausrusten" },
        { "gear.equip_already", "Ausgerustet" },
        { "gear.no_slot_items", "Noch keine Item-Kopie fuer diesen Slot." },

        { "currency.gold.name", "Gold" },
        { "currency.gems.name", "Edelsteine" },
        { "currency.myth_essence.name", "Mythos-Essenz" },
        { "currency.pass_xp.name", "Pass-EP" },

        { "role.warrior.name", "Krieger" },
        { "role.tank.name", "Tank" },
        { "role.mage.name", "Magier" },
        { "role.ranger.name", "Schütze" },
        { "role.support.name", "Unterstützung" },

        { "rarity.rare.name", "Selten" },
        { "rarity.epic.name", "Episch" },
        { "rarity.legendary.name", "Legendär" },

        { "hero.hero_astra.name", "Astra" },
        { "hero.hero_astra.title", "Die Frost-Vorhut" },
        { "hero.hero_astra.description", "Eine Frontkämpferin, die Druck in stetigen Schaden verwandelt." },
        { "hero.hero_astra.ability.name", "Gletscheransturm" },
        { "hero.hero_astra.ability.description", "Astra stürmt in die gegnerische Linie und verursacht hohen physischen Schaden." },
        { "hero.hero_borin.name", "Borin" },
        { "hero.hero_borin.title", "Der eiserne Wächter" },
        { "hero.hero_borin.description", "Ein widerstandsfähiger Tank, der das Team in langen Kämpfen am Leben hält." },
        { "hero.hero_borin.ability.name", "Ambosswacht" },
        { "hero.hero_borin.ability.description", "Borin stemmt sich hinter sein Schild und verringert eingehenden Schaden." },
        { "hero.hero_cyra.name", "Cyra" },
        { "hero.hero_cyra.title", "Das brennende Licht" },
        { "hero.hero_cyra.description", "Eine Fernkampfmagierin, die gruppierte Gegner verbrennt." },
        { "hero.hero_cyra.ability.name", "Sonnenflackern" },
        { "hero.hero_cyra.ability.description", "Cyra entfesselt eine Feuerexplosion, die den Zielbereich trifft." },
        { "hero.hero_dante.name", "Dante" },
        { "hero.hero_dante.title", "Der Riss-Schütze" },
        { "hero.hero_dante.description", "Ein präziser Schütze, der geschwächte Gegner erledigt." },
        { "hero.hero_dante.ability.name", "Rissschuss" },
        { "hero.hero_dante.ability.description", "Dante markiert eine Schwachstelle und feuert ein kritisches Projektil ab." },
        { "hero.hero_elowen.name", "Elowen" },
        { "hero.hero_elowen.title", "Das Hain-Orakel" },
        { "hero.hero_elowen.description", "Eine legendäre Unterstützung, die Verbündete heilt und das Tempo erhöht." },
        { "hero.hero_elowen.ability.name", "Grünes Gebet" },
        { "hero.hero_elowen.ability.description", "Elowen stellt Gesundheit wieder her und stärkt die Formation." },
        { "hero.hero_paladin.name", "Paladin" },
        { "hero.hero_paladin.title", "Der Morgen-Schild" },
        { "hero.hero_paladin.description", "Ein strahlender Frontkämpfer, der Verbündete schützt und mit heiligen Schlägen antwortet." },
        { "hero.hero_paladin.ability.name", "Strahlende Aegis" },
        { "hero.hero_paladin.ability.description", "Der Paladin errichtet eine heilige Barriere und kontert dann mit einem schweren Richtschlag." },
        { "hero.hero_ravik.name", "Ravik" },
        { "hero.hero_ravik.title", "Das Asche-Wunderkind" },
        { "hero.hero_ravik.description", "Ein unberechenbarer Magier, der in Ultimative-Fenstern hohen Schaden verursacht." },
        { "hero.hero_ravik.ability.name", "Asche-Nova" },
        { "hero.hero_ravik.ability.description", "Ravik entzündet gespeicherte Flammen zu einer breiten magischen Explosion." },

        { "equipment.equipment_weapon.name", "Waffe" },
        { "equipment.equipment_weapon.description", "Die aktive Waffenleiste für {0}. Verbessere sie im Ausrüstungsbildschirm, um den Angriff dieses Helden zu erhöhen." },
        { "equipment.equipment_armor.name", "Rüstung" },
        { "equipment.equipment_armor.description", "Die aktive Rüstungsleiste für {0}. Verbessere sie im Ausrüstungsbildschirm, um die Überlebensfähigkeit zu erhöhen." },

        { "accessory.item_slot_earrings.name", "Ohrringe" },
        { "accessory.item_slot_necklace.name", "Kette" },
        { "accessory.item_slot_bracelet.name", "Armband" },
        { "accessory.item_slot_gloves.name", "Handschuhe" },
        { "accessory.item_slot_shoes.name", "Schuhe" },
        { "accessory.item_slot_headgear.name", "Helm" },
        { "accessory.description", "Beute aus dem Ausrüstungs-Dungeon. Kopien können Helden ausgerüstet oder im Helden-Ausrüstungsfenster fusioniert werden." },
        { "accessory.fuse.max", "Fusion: höchste Seltenheit" },
        { "accessory.fuse.next", "Fusion: {0} Kopien -> {1}" },
        { "accessory.stats", "Besitz {0} | Inventar {1} | Ausgerüstet {2}\nLv 1: +{3} ATK, +{4} HP\nMax Lv {5}: +{6} ATK, +{7} HP\n{8}" },
        { "accessory.action.invalid", "Unbekanntes Accessoire: {0}" },
        { "accessory.action.equip.missing", "Keine Kopie von {0} zum Anlegen." },
        { "accessory.action.equip.already", "{0} ist bei {1} bereits angelegt." },
        { "accessory.action.equip.success", "{0} bei {1} angelegt." },
        { "accessory.action.unequip.not_equipped", "{0} ist bei {1} nicht angelegt." },
        { "accessory.action.unequip.success", "{0} von {1} abgelegt." },
        { "accessory.action.level.max", "{0} {1} ist bereits Max. Level." },
        { "accessory.action.level.insufficient", "Brauche {0} {1}, um {2} zu verbessern." },
        { "accessory.action.level.success", "{0} {1} erreicht {2}. {3}." },
        { "accessory.action.fuse.missing", "Brauche {0}x {1} zum Fusionieren." },
        { "accessory.action.fuse.success", "Fusioniert zu {0}." },

        { "dungeon.gold_dungeon.name", "Gold-Dungeon" },
        { "dungeon.gold_dungeon.selector", "Goldtresor" },
        { "dungeon.gold_dungeon.set", "Goldschatz-Set" },
        { "dungeon.gold_dungeon.boss", "Schatzgolem" },
        { "dungeon.essence_dungeon.name", "Essenz-Dungeon" },
        { "dungeon.essence_dungeon.selector", "Essenzhain" },
        { "dungeon.essence_dungeon.set", "Riss-Essenz-Set" },
        { "dungeon.essence_dungeon.boss", "Rissdrache" },
        { "dungeon.gear_dungeon.name", "Ausrüstungs-Dungeon" },
        { "dungeon.gear_dungeon.selector", "Ausrustungs-Schmiede" },
        { "dungeon.gear_dungeon.set", "Eiserne Waffenkammer" },
        { "dungeon.gear_dungeon.boss", "Eisenhund" },
        { "dungeon.tower_dungeon.name", "Turm-Dungeon" },
        { "dungeon.tower_dungeon.selector", "Turm der Pruefung" },
        { "dungeon.tower_dungeon.set", "Pruefungsturm" },
        { "dungeon.tower_dungeon.boss", "Apex-Waechter" },
        { "dungeon.default_result", "Dungeons sind die aktive Quelle für Ressourcen." },
        { "dungeon.flow_hint", "{0} waehlen, Formation oeffnen, Etage {1} clearen, dann Rewards in Upgrades stecken." },
        { "dungeon.future_locked", "Gesperrt" },
        { "dungeon.future_detail", "Spaeterer Dungeon" },
        { "dungeon.progress_line", "Fortschritt: <color=#F8E85A>{0}/{1}</color>   Etage {2}" },
        { "dungeon.meta.reward", "{0} | Empf. {1} | +{2} {3}" },
        { "dungeon.meta.drop", "{0} | Empf. {1} | Drop: Ausrüstung" },
        { "dungeon.preview.reward", "{0} F{1}  Empf. {2}\nBoss-HP {3}  +{4} {5}" },
        { "dungeon.preview.drop", "{0} F{1}  Empf. {2}\nBoss-HP {3}  Ausrüstungsbeute" },
        { "dungeon.reward.drop", "Belohnung: zufällige Ausrüstungsbeute" },
        { "dungeon.reward.currency", "Belohnung: +{0} {1}" },

        { "home.next_goal.title", "Naechstes Ziel" },
        { "home.next_goal.push_campaign", "Kampagne Stufe {0} pushen ({1})" },
        { "home.next_goal.equip_drops", "Ausrustungs-Drops anlegen, dann Stufe {0} erneut versuchen ({1})" },
        { "home.next_goal.upgrade_weapon", "Waffe fuer ATK verbessern ({0}/{1} {2})" },
        { "home.next_goal.upgrade_armor", "Ruestung fuer HP verbessern ({0}/{1} {2})" },
        { "home.next_goal.level_accessory", "Angelegtes Accessoire leveln ({0}/{1} {2})" },
        { "home.next_goal.level_hero", "{0} leveln ({1}/{2} {3})" },
        { "home.next_goal.upgrade_village", "Village {0} aufwerten ({1}/{2} {3})" },
        { "home.next_goal.build_village", "Village {0} bauen ({1}/{2} {3})" },
        { "home.next_goal.run_gold", "Gold-Dungeon F{0} fuer Upgrade-Gold spielen (Macht {1}/{2})" },
        { "home.next_goal.run_essence", "Essenz-Dungeon F{0} fuer Helden-Essenz spielen (Macht {1}/{2})" },
        { "home.next_goal.run_gear", "Ausrustungs-Dungeon F{0} fuer Drops spielen (Macht {1}/{2})" },
        { "home.next_goal.summon", "x1 beschwoeren fuer Splitter ({0}/{1} {2})" },
        { "home.next_goal.farm_loop", "Farm-Loop: +{0} Macht, {1} {2}, {3} {4}" },
        { "home.next_goal.result_prefix", "Naechstes Ziel: {0}" },

        { "item.mission_xp.name", "Missions-EP" },
        { "item.mission_xp.detail", "Missionspfad" },
        { "item.mission_xp.description", "Fortschritt aus täglichen Missionen. Er füllt den Missionspfad und schaltet Belohnungsstufen frei." },
        { "item.mission_xp.stats", "Gespeicherte EP: {0}\nSichtbar in: {1}\nQuellen: tägliche Missionsbelohnungen" },

        { "account.start.title", "Mythwake" },
        { "account.start.subtitle", "Waehle, wie dieser Tester-Build Fortschritt laden soll." },
        { "account.start.continue", "Weiter" },
        { "account.start.guest", "Als Gast spielen" },
        { "account.start.email_login", "Mit Email einloggen" },
        { "account.start.register", "Account erstellen" },
        { "account.start.google_later", "Google Play Login kommt spaeter; fuer diesen Test Email nutzen." },
        { "account.start.local.present", "Lokaler Save: auf diesem Geraet vorhanden" },
        { "account.start.local.none", "Lokaler Save: keiner auf diesem Geraet" },
        { "account.start.session.none", "Server-Account: nicht eingeloggt" },
        { "account.start.session.present", "Server-Account: {0} ({1})" },
        { "account.start.session.kind.none", "Kein Account" },
        { "account.start.session.kind.email", "Email-Account" },
        { "account.start.session.kind.guest", "Gast-Session" },
        { "account.start.mode", "Spielmodus: {0}" },
        { "account.start.player", "Spieler: {0}" },
        { "account.start.status.ready", "Bereit. Weiter laedt gespeicherten Fortschritt. Email behaelt Server-Fortschritt; Gast ist fuer kurze Tests." },
        { "account.start.status.continuing", "Gespeicherte Server-Session wird geladen..." },
        { "account.start.status.guest_starting", "Gast-Session wird gestartet..." },
        { "account.start.status.guest_failed", "Gast-Backend nicht erreichbar: {0}. Lokaler Gastmodus startet." },
        { "account.start.status.no_continue", "Noch kein Fortschritt gefunden. Account erstellen, einloggen oder als Gast spielen." },
        { "account.start.status.logged_out", "Ausgeloggt. Server-Fortschritt bleibt am Account; zum Wiederherstellen erneut einloggen." },
        { "account.start.local_continue_result", "Lokaler Speicherstand fortgesetzt. Server-Account-Fortschritt wurde nicht geaendert." },
        { "account.start.local_guest_result", "Lokaler Gastmodus gestartet. Backend-Gast-Auth ist gerade nicht erreichbar." },
        { "account.start.server_continue_result", "Server-Fortschritt fuer diesen Account geladen." },
        { "account.start.server_bootstrap_failed_result", "Server-Session ist aktiv, aber Bootstrap ist fehlgeschlagen: {0}" },
        { "account.start.email.title.login", "Email Login" },
        { "account.start.email.title.register", "Registrieren" },
        { "account.start.email.submit.login", "Login" },
        { "account.start.email.submit.register", "Registrieren" },
        { "account.start.email.back", "Zurueck" },
        { "account.start.email.status.login", "Mit Email-Account den Server-Fortschritt wiederherstellen." },
        { "account.start.email.status.register", "Tester-Account erstellen. Passwort mindestens 8 Zeichen." },
        { "account.start.email.status.busy", "Bitte auf die laufende Backend-Anfrage warten." },
        { "account.start.email.status.working", "Server wird kontaktiert..." },
        { "account.start.email.error.invalid_email", "Bitte eine gueltige Email-Adresse eingeben." },
        { "account.start.email.error.weak_password", "Bitte ein Passwort mit mindestens 8 Zeichen nutzen." },
        { "account.start.email.error.duplicate", "Diese Email hat bereits einen Account. Bitte Mit Email einloggen nutzen." },
        { "account.start.email.error.credentials", "Email oder Passwort ist falsch. Bitte beides pruefen und erneut versuchen." },
        { "account.start.email.error.backend_down", "Server ist nicht erreichbar. Backend/WLAN pruefen oder als Gast lokal testen." },
        { "account.start.email.error.generic", "Account-Anfrage fehlgeschlagen: {0}" },

        { "management.title", "Verwaltung" },
        { "management.profile", "Profil" },
        { "management.options", "Optionen" },
        { "management.account", "Account" },
        { "management.support", "Support" },
        { "management.about", "Info" },
        { "management.profile.title", "Spielerprofil" },
        { "management.profile.body", "{0}\nTeamstärke: {1}\nKampagnenstufe: {2}\nGold: {3}\nEdelsteine: {4}" },
        { "management.options.title", "Optionen" },
        { "management.options.body", "Sprache: {0}\nSpielmodus: {1}\nPerformance-Overlay: {2}" },
        { "management.backend.server", "Server" },
        { "management.backend.local", "Lokal" },
        { "management.language.switch", "Sprache wechseln" },
        { "management.performance.on", "An" },
        { "management.performance.off", "Aus" },
        { "management.performance.show", "FPS anzeigen" },
        { "management.performance.hide", "FPS ausblenden" },
        { "management.account.title", "Account" },
        { "management.account.body", "Build: Prototype v{1} / Save v{2}\nModus: {3}\nSession: {4}\nSpieler-ID: {0}\nLogout loescht nur die Geraete-Session. Dev Reset loescht den aktuellen Server-Spieler." },
        { "management.session.email", "Email-Account aktiv" },
        { "management.session.guest", "Gast-Session aktiv" },
        { "management.session.none", "Keine Backend-Session" },
        { "management.support.title", "Support" },
        { "management.support.body", "Support-Werkzeuge, Feedback und Fehlerberichte werden hier gesammelt, sobald die Live-Service-Schicht bereit ist." },
        { "management.about.title", "Über Mythwake" },
        { "management.about.body", "Prototype-Version: {0}\nSpeicherstand-Schema: {1}\nMythwake läuft derzeit als Idle-RPG-Prototyp in Entwicklung." },

        { "summon.banner.hero_shard_standard.name", "Helden erwecken" },
        { "summon.banner.hero_shard_standard.promo", "Das erste x10-Paket hat 10% Rabatt" },
        { "summon.banner.hero_shard_vanguard.name", "Schwur der Vorhut" },
        { "summon.banner.hero_shard_vanguard.promo", "Höhere epische Chance für Frontteams" },
        { "summon.banner.hero_shard_mystic.name", "Mystische Blüte" },
        { "summon.banner.hero_shard_mystic.promo", "Bessere legendäre Chancen für Unterstützung und Magier" },
        { "summon.result.title", "Beschwörungsergebnis" },
        { "summon.result.title_count", "Beschwörung x{0}" },
        { "summon.result.summary.single", "{0} x{1} | +{2} Splitter" },
        { "summon.result.summary.multi", "{0} Helden in x{1} | +{2} Splitter" },
        { "summon.result.summary.empty", "Beschwörung x{0} abgeschlossen" },
        { "summon.result.shard_hint", "Splitter geben sofort kleine Werte; genug Duplikate schalten Aufstieg frei." },
        { "summon.result.auto", "Auto-Beschwörung" },
        { "summon.result.auto_remaining", "Auto-Beschwörung {0}" },
        { "formation.auto_next", "Auto-weiter nach Sieg (Skills AUTO)" },
        { "formation.auto_battle", "Auto-Kampf" },
        { "formation.begin_battle", "Kampf starten" },
        { "formation.deployed", "Aufgestellte Helden" },
        { "formation.player_power", "Deine Kraft" },
        { "formation.enemy_power", "Gegnerkraft" },
        { "formation.hint.swap", "Leuchtenden Slot zum Tauschen antippen." },
        { "formation.hint.server", "Server-Modus berechnet Belohnungen und zeigt dann den Kampf." },
        { "formation.hint.dungeon", "Kampf starten spielt einmal. Auto-Kampf laeuft weiter bis Stopp oder Niederlage." },
        { "formation.hint.campaign", "Kampf starten spielt einmal. Auto-Kampf laeuft weiter bis Stopp oder Niederlage." }
    };
}
