CREATE TABLE IF NOT EXISTS common.village_building_definitions (
	id text PRIMARY KEY,
	slot_index integer NOT NULL CHECK (slot_index >= 0 AND slot_index < 12),
	building_option_index integer NOT NULL CHECK (building_option_index >= 0 AND building_option_index < 3),
	display_name text NOT NULL,
	texture_name text NOT NULL,
	build_cost integer NOT NULL CHECK (build_cost >= 0),
	max_level integer NOT NULL CHECK (max_level > 0),
	upgrade_cost_per_level integer NOT NULL CHECK (upgrade_cost_per_level > 0),
	bonus_type text NOT NULL,
	bonus_value_per_level numeric(10,4) NOT NULL CHECK (bonus_value_per_level >= 0),
	active boolean NOT NULL DEFAULT true,
	UNIQUE (slot_index, building_option_index)
);

INSERT INTO common.village_building_definitions (
	id,
	slot_index,
	building_option_index,
	display_name,
	texture_name,
	build_cost,
	max_level,
	upgrade_cost_per_level,
	bonus_type,
	bonus_value_per_level,
	active
) VALUES
	('village_building_01_option_01', 0, 0, 'Rathaus', 'VillageBuildings/village_building_01_option_01_town_hall', 5, 20, 5, 'team_health', 24.0000, true),
	('village_building_01_option_02', 0, 1, 'Gildenhalle', 'VillageBuildings/village_building_01_option_02_guild_hall', 7, 20, 5, 'team_health', 28.0000, true),
	('village_building_01_option_03', 0, 2, 'Ratssitz', 'VillageBuildings/village_building_01_option_03_council_keep', 9, 20, 5, 'team_health', 32.0000, true),
	('village_building_02_option_01', 1, 0, 'Heldenkaserne', 'VillageBuildings/village_building_02_option_01_hero_barracks', 5, 20, 5, 'team_attack', 3.0000, true),
	('village_building_02_option_02', 1, 1, 'Trainingsdojo', 'VillageBuildings/village_building_02_option_02_training_dojo', 7, 20, 5, 'team_attack', 4.0000, true),
	('village_building_02_option_03', 1, 2, 'Heldenhaus', 'VillageBuildings/village_building_02_option_03_hero_lodge', 9, 20, 5, 'team_attack', 5.0000, true),
	('village_building_03_option_01', 2, 0, 'Arkanportal', 'VillageBuildings/village_building_03_option_01_arcane_portal', 5, 20, 5, 'afk_essence_rate', 0.0500, true),
	('village_building_03_option_02', 2, 1, 'Runentor', 'VillageBuildings/village_building_03_option_02_rune_gate', 7, 20, 5, 'afk_essence_rate', 0.0700, true),
	('village_building_03_option_03', 2, 2, 'Kristallobelisk', 'VillageBuildings/village_building_03_option_03_crystal_obelisk', 9, 20, 5, 'afk_essence_rate', 0.0900, true),
	('village_building_04_option_01', 3, 0, 'Schmiede', 'VillageBuildings/village_building_04_option_01_blacksmith', 5, 20, 5, 'team_attack', 3.0000, true),
	('village_building_04_option_02', 3, 1, 'Waffenkammer', 'VillageBuildings/village_building_04_option_02_armory', 7, 20, 5, 'team_attack', 4.0000, true),
	('village_building_04_option_03', 3, 2, 'Schmelzwerk', 'VillageBuildings/village_building_04_option_03_furnace_workshop', 9, 20, 5, 'team_attack', 5.0000, true),
	('village_building_05_option_01', 4, 0, 'Magierturm', 'VillageBuildings/village_building_05_option_01_mage_tower', 5, 20, 5, 'afk_essence_rate', 0.0500, true),
	('village_building_05_option_02', 4, 1, 'Observatorium', 'VillageBuildings/village_building_05_option_02_observatory', 7, 20, 5, 'afk_essence_rate', 0.0700, true),
	('village_building_05_option_03', 4, 2, 'Zauberbibliothek', 'VillageBuildings/village_building_05_option_03_spell_library', 9, 20, 5, 'afk_essence_rate', 0.0900, true),
	('village_building_06_option_01', 5, 0, 'Marktstaende', 'VillageBuildings/village_building_06_option_01_market_stalls', 5, 20, 5, 'afk_gold_rate', 0.0800, true),
	('village_building_06_option_02', 5, 1, 'Handelsposten', 'VillageBuildings/village_building_06_option_02_trade_post', 7, 20, 5, 'afk_gold_rate', 0.1100, true),
	('village_building_06_option_03', 5, 2, 'Basarzelt', 'VillageBuildings/village_building_06_option_03_bazaar_tent', 9, 20, 5, 'afk_gold_rate', 0.1400, true),
	('village_building_07_option_01', 6, 0, 'Lagerhaus', 'VillageBuildings/village_building_07_option_01_warehouse', 5, 20, 5, 'afk_gold_rate', 0.0800, true),
	('village_building_07_option_02', 6, 1, 'Kornspeicher', 'VillageBuildings/village_building_07_option_02_granary', 7, 20, 5, 'afk_gold_rate', 0.1100, true),
	('village_building_07_option_03', 6, 2, 'Vorratslager', 'VillageBuildings/village_building_07_option_03_supply_depot', 9, 20, 5, 'afk_gold_rate', 0.1400, true),
	('village_building_08_option_01', 7, 0, 'Zimmererhof', 'VillageBuildings/village_building_08_option_01_carpenter_yard', 5, 20, 5, 'team_health', 24.0000, true),
	('village_building_08_option_02', 7, 1, 'Bauwerkstatt', 'VillageBuildings/village_building_08_option_02_builder_workshop', 7, 20, 5, 'team_health', 28.0000, true),
	('village_building_08_option_03', 7, 2, 'Artefaktladen', 'VillageBuildings/village_building_08_option_03_artificer_shop', 9, 20, 5, 'team_health', 32.0000, true),
	('village_building_09_option_01', 8, 0, 'Taverne', 'VillageBuildings/village_building_09_option_01_tavern', 5, 20, 5, 'team_health', 24.0000, true),
	('village_building_09_option_02', 8, 1, 'Gasthaus', 'VillageBuildings/village_building_09_option_02_inn', 7, 20, 5, 'team_health', 28.0000, true),
	('village_building_09_option_03', 8, 2, 'Festhalle', 'VillageBuildings/village_building_09_option_03_feast_hall', 9, 20, 5, 'team_health', 32.0000, true),
	('village_building_10_option_01', 9, 0, 'Alchemielabor', 'VillageBuildings/village_building_10_option_01_alchemy_lab', 5, 20, 5, 'afk_essence_rate', 0.0500, true),
	('village_building_10_option_02', 9, 1, 'Kraeuterhuette', 'VillageBuildings/village_building_10_option_02_herbalist_hut', 7, 20, 5, 'afk_essence_rate', 0.0700, true),
	('village_building_10_option_03', 9, 2, 'Trankladen', 'VillageBuildings/village_building_10_option_03_potion_shop', 9, 20, 5, 'afk_essence_rate', 0.0900, true),
	('village_building_11_option_01', 10, 0, 'Feldhof', 'VillageBuildings/village_building_11_option_01_crop_farm', 5, 20, 5, 'afk_gold_rate', 0.0800, true),
	('village_building_11_option_02', 10, 1, 'Tiergatter', 'VillageBuildings/village_building_11_option_02_animal_pen', 7, 20, 5, 'afk_gold_rate', 0.1100, true),
	('village_building_11_option_03', 10, 2, 'Obsthain', 'VillageBuildings/village_building_11_option_03_orchard', 9, 20, 5, 'afk_gold_rate', 0.1400, true),
	('village_building_12_option_01', 11, 0, 'Schrein', 'VillageBuildings/village_building_12_option_01_shrine', 5, 20, 5, 'team_attack', 3.0000, true),
	('village_building_12_option_02', 11, 1, 'Wachturm', 'VillageBuildings/village_building_12_option_02_watchtower', 7, 20, 5, 'team_attack', 4.0000, true),
	('village_building_12_option_03', 11, 2, 'Gartenhain', 'VillageBuildings/village_building_12_option_03_garden_grove', 9, 20, 5, 'team_attack', 5.0000, true)
ON CONFLICT (id) DO UPDATE SET
	slot_index = EXCLUDED.slot_index,
	building_option_index = EXCLUDED.building_option_index,
	display_name = EXCLUDED.display_name,
	texture_name = EXCLUDED.texture_name,
	build_cost = EXCLUDED.build_cost,
	max_level = EXCLUDED.max_level,
	upgrade_cost_per_level = EXCLUDED.upgrade_cost_per_level,
	bonus_type = EXCLUDED.bonus_type,
	bonus_value_per_level = EXCLUDED.bonus_value_per_level,
	active = EXCLUDED.active;
