CREATE TABLE IF NOT EXISTS common.tower_definitions (
	 id text PRIMARY KEY,
	 display_name text NOT NULL,
	 max_floor integer NOT NULL CHECK (max_floor > 0),
	 section_size integer NOT NULL CHECK (section_size > 0),
	 mini_boss_interval integer NOT NULL CHECK (mini_boss_interval > 0),
	 big_boss_interval integer NOT NULL CHECK (big_boss_interval > 0),
	 shard_interval integer NOT NULL CHECK (shard_interval > 0),
	 base_required_power integer NOT NULL CHECK (base_required_power >= 0),
	 required_power_scale double precision NOT NULL CHECK (required_power_scale >= 0),
	 required_power_growth double precision NOT NULL CHECK (required_power_growth > 0),
	 base_reward_gold integer NOT NULL CHECK (base_reward_gold >= 0),
	 reward_gold_scale double precision NOT NULL CHECK (reward_gold_scale >= 0),
	 reward_gold_growth double precision NOT NULL CHECK (reward_gold_growth > 0),
	 base_reward_essence integer NOT NULL CHECK (base_reward_essence >= 0),
	 reward_essence_scale double precision NOT NULL CHECK (reward_essence_scale >= 0),
	 reward_essence_growth double precision NOT NULL CHECK (reward_essence_growth > 0),
	 base_enemy_hp integer NOT NULL CHECK (base_enemy_hp >= 0),
	 enemy_hp_scale double precision NOT NULL CHECK (enemy_hp_scale >= 0),
	 enemy_hp_growth double precision NOT NULL CHECK (enemy_hp_growth > 0),
	 base_enemy_damage integer NOT NULL CHECK (base_enemy_damage >= 0),
	 enemy_damage_scale double precision NOT NULL CHECK (enemy_damage_scale >= 0),
	 enemy_damage_growth double precision NOT NULL CHECK (enemy_damage_growth > 0),
	 normal_enemy_hp_multiplier double precision NOT NULL CHECK (normal_enemy_hp_multiplier > 0),
	 mini_boss_enemy_hp_multiplier double precision NOT NULL CHECK (mini_boss_enemy_hp_multiplier > 0),
	 big_boss_enemy_hp_multiplier double precision NOT NULL CHECK (big_boss_enemy_hp_multiplier > 0),
	 normal_enemy_damage_multiplier double precision NOT NULL CHECK (normal_enemy_damage_multiplier > 0),
	 mini_boss_enemy_damage_multiplier double precision NOT NULL CHECK (mini_boss_enemy_damage_multiplier > 0),
	 big_boss_enemy_damage_multiplier double precision NOT NULL CHECK (big_boss_enemy_damage_multiplier > 0),
	 normal_recommended_power_multiplier double precision NOT NULL CHECK (normal_recommended_power_multiplier > 0),
	 mini_boss_recommended_power_multiplier double precision NOT NULL CHECK (mini_boss_recommended_power_multiplier > 0),
	 big_boss_recommended_power_multiplier double precision NOT NULL CHECK (big_boss_recommended_power_multiplier > 0),
	 normal_shard_base integer NOT NULL CHECK (normal_shard_base >= 0),
	 normal_shard_every_floors integer NOT NULL CHECK (normal_shard_every_floors > 0),
	 mini_boss_shard_base integer NOT NULL CHECK (mini_boss_shard_base >= 0),
	 mini_boss_shard_every_floors integer NOT NULL CHECK (mini_boss_shard_every_floors > 0),
	 big_boss_shard_base integer NOT NULL CHECK (big_boss_shard_base >= 0),
	 big_boss_shard_every_floors integer NOT NULL CHECK (big_boss_shard_every_floors > 0),
	 max_combat_seconds integer NOT NULL CHECK (max_combat_seconds > 0),
	 updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO common.tower_definitions (
	id, display_name, max_floor, section_size, mini_boss_interval, big_boss_interval, shard_interval,
	base_required_power, required_power_scale, required_power_growth,
	base_reward_gold, reward_gold_scale, reward_gold_growth,
	base_reward_essence, reward_essence_scale, reward_essence_growth,
	base_enemy_hp, enemy_hp_scale, enemy_hp_growth,
	base_enemy_damage, enemy_damage_scale, enemy_damage_growth,
	normal_enemy_hp_multiplier, mini_boss_enemy_hp_multiplier, big_boss_enemy_hp_multiplier,
	normal_enemy_damage_multiplier, mini_boss_enemy_damage_multiplier, big_boss_enemy_damage_multiplier,
	normal_recommended_power_multiplier, mini_boss_recommended_power_multiplier, big_boss_recommended_power_multiplier,
	normal_shard_base, normal_shard_every_floors, mini_boss_shard_base, mini_boss_shard_every_floors,
	big_boss_shard_base, big_boss_shard_every_floors, max_combat_seconds
) VALUES (
	'tower_dungeon', 'Tower Dungeon', 1000, 100, 25, 100, 10,
	185, 74, 1.12,
	55, 16, 1.08,
	14, 5, 1.04,
	18, 5.8, 1.08,
	105, 34, 1.12,
	0.86, 1.55, 2.35,
	0.92, 1.28, 1.62,
	1, 1.38, 2.05,
	1, 250, 4, 200, 12, 100, 30
)
ON CONFLICT (id) DO UPDATE SET
	display_name = EXCLUDED.display_name,
	max_floor = EXCLUDED.max_floor,
	section_size = EXCLUDED.section_size,
	mini_boss_interval = EXCLUDED.mini_boss_interval,
	big_boss_interval = EXCLUDED.big_boss_interval,
	shard_interval = EXCLUDED.shard_interval,
	base_required_power = EXCLUDED.base_required_power,
	required_power_scale = EXCLUDED.required_power_scale,
	required_power_growth = EXCLUDED.required_power_growth,
	base_reward_gold = EXCLUDED.base_reward_gold,
	reward_gold_scale = EXCLUDED.reward_gold_scale,
	reward_gold_growth = EXCLUDED.reward_gold_growth,
	base_reward_essence = EXCLUDED.base_reward_essence,
	reward_essence_scale = EXCLUDED.reward_essence_scale,
	reward_essence_growth = EXCLUDED.reward_essence_growth,
	base_enemy_hp = EXCLUDED.base_enemy_hp,
	enemy_hp_scale = EXCLUDED.enemy_hp_scale,
	enemy_hp_growth = EXCLUDED.enemy_hp_growth,
	base_enemy_damage = EXCLUDED.base_enemy_damage,
	enemy_damage_scale = EXCLUDED.enemy_damage_scale,
	enemy_damage_growth = EXCLUDED.enemy_damage_growth,
	normal_enemy_hp_multiplier = EXCLUDED.normal_enemy_hp_multiplier,
	mini_boss_enemy_hp_multiplier = EXCLUDED.mini_boss_enemy_hp_multiplier,
	big_boss_enemy_hp_multiplier = EXCLUDED.big_boss_enemy_hp_multiplier,
	normal_enemy_damage_multiplier = EXCLUDED.normal_enemy_damage_multiplier,
	mini_boss_enemy_damage_multiplier = EXCLUDED.mini_boss_enemy_damage_multiplier,
	big_boss_enemy_damage_multiplier = EXCLUDED.big_boss_enemy_damage_multiplier,
	normal_recommended_power_multiplier = EXCLUDED.normal_recommended_power_multiplier,
	mini_boss_recommended_power_multiplier = EXCLUDED.mini_boss_recommended_power_multiplier,
	big_boss_recommended_power_multiplier = EXCLUDED.big_boss_recommended_power_multiplier,
	normal_shard_base = EXCLUDED.normal_shard_base,
	normal_shard_every_floors = EXCLUDED.normal_shard_every_floors,
	mini_boss_shard_base = EXCLUDED.mini_boss_shard_base,
	mini_boss_shard_every_floors = EXCLUDED.mini_boss_shard_every_floors,
	big_boss_shard_base = EXCLUDED.big_boss_shard_base,
	big_boss_shard_every_floors = EXCLUDED.big_boss_shard_every_floors,
	max_combat_seconds = EXCLUDED.max_combat_seconds,
	updated_at = now();

CREATE TABLE IF NOT EXISTS player.player_tower_progress (
	player_id text PRIMARY KEY REFERENCES account.players(id) ON DELETE CASCADE,
	highest_unlocked_floor integer NOT NULL DEFAULT 1 CHECK (highest_unlocked_floor >= 1),
	highest_cleared_floor integer NOT NULL DEFAULT 0 CHECK (highest_cleared_floor >= 0),
	selected_floor integer NOT NULL DEFAULT 1 CHECK (selected_floor >= 1),
	section_start_floor integer NOT NULL DEFAULT 1 CHECK (section_start_floor >= 1),
	updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE VIEW debug.v_player_tower_overview AS
SELECT
	p.id AS player_id,
	COALESCE(t.highest_unlocked_floor, 1) AS highest_unlocked_floor,
	COALESCE(t.highest_cleared_floor, 0) AS highest_cleared_floor,
	COALESCE(t.selected_floor, 1) AS selected_floor,
	COALESCE(t.section_start_floor, 1) AS section_start_floor,
	COALESCE(t.updated_at, p.updated_at) AS updated_at,
	definition.max_floor,
	definition.section_size
FROM account.players p
LEFT JOIN player.player_tower_progress t ON t.player_id = p.id
LEFT JOIN common.tower_definitions definition ON definition.id = 'tower_dungeon';
